# fly.toml app configuration file generated for apibackendaxa on 2023-05-01T09:33:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apibackendaxa"
primary_region = "mad"
kill_signal = "SIGINT"
kill_timeout = "5s"
processes = []

[env]
  KEY_JWT = "aKLMSLK3I4JNESOLUTIONSKJN545N4J5N4J54H4G44H5JBSSDBAXAAXA"
  POLICIES_URL_BASE = "http://www.mocky.io"
  PORT = "3000"
  USER_URL_BASE = "http://www.mocky.io"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
